# Generated by Django 5.1.3 on 2024-11-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='etoiles',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offres_voyages/'),
        ),
        migrations.AlterField(
            model_name='offrevoyage',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('sejour', 'Sejour & Vol')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.BooleanField(default=False, verbose_name='En attente de confirmation'),
        ),
    ]
