# Generated by Django 5.1.3 on 2024-11-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotel_etoiles_offrevoyage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offrevoyage',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='offrevoyage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='offrevoyage',
            name='price',
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='commentaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='destination_pays',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='destination_ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='details_offre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='durees_disponibles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='equipement_chambre',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='equipement_hotel',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='etablissement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='include_flight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='informations_complementaires',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='liste_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='min_price_w_flight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='nb_etoiles',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='note',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='presentation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offrevoyage',
            name='type',
            field=models.CharField(choices=[('sejour', 'Séjour')], max_length=10),
        ),
    ]
